# coding: utf-8

"""
    Swagger Delivery

    Отвечает за учет курьеров, деспетчеризацию доставкуов, доставку

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from fastapi.responses import RedirectResponse
from fastapi.middleware.cors import CORSMiddleware

from api.adapters.http.contract.src.api.apis.default_api import router as DefaultApiRouter
from api.adapters.jobs.scheduler import start_jobs

app = FastAPI(
    title="Swagger Delivery",
    description="Отвечает за учет курьеров, деспетчеризацию доставкуов, доставку",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)

# Настройка CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:8086"],
    allow_credentials=True,
    allow_methods=["*"],  # Разрешить все методы (GET, POST, PUT и т. д.)
    allow_headers=["*"],  # Разрешить все заголовки
)

@app.get("/")
async def read_root():
    return {"message": "Hello, CORS is working!"}

scheduler = start_jobs()

@app.on_event("shutdown")
def shutdown_event():
    scheduler.shutdown()
