# coding: utf-8

"""
    Swagger Delivery

    Отвечает за учет курьеров, деспетчеризацию доставкуов, доставку

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI
from fastapi.responses import RedirectResponse

from api.adapters.http.contract.src.api.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Swagger Delivery",
    description="Отвечает за учет курьеров, деспетчеризацию доставкуов, доставку",
    version="1.0.0",
)

app.include_router(DefaultApiRouter)

@app.get("/", include_in_schema=False)
def redirect_to_docs():
    return RedirectResponse(url="/docs#/")
