services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ddd_user
      POSTGRES_PASSWORD: ddd_password
      POSTGRES_DB: ddd_delivery
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ddd_user -d ddd_delivery"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: